(()=>{
const qs=new URLSearchParams(location.search);const code=qs.get('lang')||'en';const data=(window.LW_COURSE_V48||{})[code]||window.LW_COURSE_V48.en;
const $=s=>document.querySelector(s);const key='lernwerkCourseV48';
function state(){try{return JSON.parse(localStorage.getItem(key)||'{}')}catch{return{}}}function save(s){localStorage.setItem(key,JSON.stringify(s));}
function langState(){const s=state();s[code]=s[code]||{completed:{},best:{},xp:0,last:1};return [s,s[code]]}
function addGlobalXP(n){try{let s=JSON.parse(localStorage.getItem('sprachwerkQuest')||'{}');s.xp=(s.xp||0)+n;s.dailyXP=(s.dailyXP||0)+n;localStorage.setItem('sprachwerkQuest',JSON.stringify(s));window.SprachwerkCloud?.queueSave?.()}catch(e){}}
function norm(x){return String(x||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[¿¡!?.,;:'“”„\-—]/g,'').replace(/\s+/g,' ').trim()}
function esc(x){return String(x).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function speak(t){if(!('speechSynthesis'in window))return; speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang=data.voice;u.rate=.88;speechSynthesis.speak(u)}
function shuffled(a){return [...a].sort(()=>Math.random()-.5)}
let current=1,step=0,answers=[],score=0,locked=false;
const flag='/shared-assets/flags/'+data.flag+'.svg';
$('#lw48-name').textContent=data.name;const supportEl=$('#lw48-support');if(supportEl) supportEl.textContent=data.support||'';$('#lw48-flag').src=flag;document.title='LERNWERK · '+data.name+' Kurs';
function stats(){const [s,ls]=langState(),done=Object.keys(ls.completed).length,pct=Math.round(done/data.lessons.length*100);$('#lw48-xp').textContent=ls.xp||0;$('#lw48-done').textContent=done+'/'+data.lessons.length;$('#lw48-pct').textContent=pct+'%';$('#lw48-coursebar').style.width=pct+'%';}
function isUnlocked(id){const [s,ls]=langState();return id===1||!!ls.completed[id-1]||!!ls.completed[id]}
function map(){const [s,ls]=langState();const list=$('#lw48-lessons');list.innerHTML=data.lessons.map(l=>{const done=!!ls.completed[l.id],unlock=isUnlocked(l.id);return `<button class="lw48-lesson ${done?'done':''} ${current===l.id?'active':''} ${unlock?'':'locked'}" data-id="${l.id}" ${unlock?'':'disabled'}><span class="lw48-node">${done?'✓':l.id}</span><span><b>${esc(l.title)}</b><small>${l.level} · ${l.xp} XP</small></span><span class="lw48-lock">${unlock?(done?'★':'›'):'🔒'}</span></button>`}).join('');list.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>{current=+b.dataset.id;const [a,ls2]=langState();ls2.last=current;save(a);startIntro();map();if(innerWidth<861)$('#lw48-map').classList.remove('mobile-open')})}
function lesson(){return data.lessons.find(x=>x.id===current)||data.lessons[0]}
function stages(l){const pairs=l.pairs;const other=data.lessons.flatMap(x=>x.pairs).filter(x=>!pairs.includes(x));const mc=(prompt,correct,field)=>{const pool=shuffled(other).slice(0,3).map(x=>x[field]);return {type:'mc',prompt,correct,options:shuffled([correct,...pool])}};return [
 {type:'learn',title:'Lernziel',copy:l.objective},
 {type:'learnphrases',title:'Schlüsselphrasen'},
 mc(`Was bedeutet „${pairs[0].target}“?`,pairs[0].base,'base'),
 mc(`Wie sagst du „${pairs[1].base}“?`,pairs[1].target,'target'),
 {type:'type',prompt:`Übersetze: ${pairs[2].base}`,answer:pairs[2].target},
 {type:'order',prompt:`Baue den Satz: ${pairs[3].base}`,answer:pairs[3].target},
 {type:'listen',prompt:'Höre zu und wähle die passende Bedeutung.',say:pairs[1].target,correct:pairs[1].base,options:shuffled([pairs[1].base,...shuffled(other).slice(0,3).map(x=>x.base)])},
 {type:'type',prompt:`Schreibe auf ${data.name}: ${pairs[0].base}`,answer:pairs[0].target},
 {type:'finish'}]}
function header(l,idx,total){$('#lw48-lesson-title').textContent=`Lektion ${l.id} · ${l.title}`;$('#lw48-lesson-sub').textContent=l.objective;$('#lw48-stepbar').style.width=Math.min(100,Math.round(idx/(total-1)*100))+'%'}
function startIntro(){step=0;score=0;answers=[];locked=false;render()}
function render(){const l=lesson(),ss=stages(l),x=ss[step];header(l,step,ss.length);const stage=$('#lw48-stage'); if(x.type==='finish'){finish(stage,l);return}
 let body='';if(x.type==='learn'){body=`<span class="lw48-stage-label">Warum diese Lektion?</span><h3>${esc(l.title)}</h3><p>${esc(x.copy)}</p><div class="lw48-tip"><strong>Grammatik-Tipp</strong><br>${esc(l.tip)}</div><div class="lw48-actions"><button class="lw48-btn teal" id="next">Lektion starten</button></div>`}
 if(x.type==='learnphrases'){body=`<span class="lw48-stage-label">Input</span><h3>Vier Sätze, die du wirklich brauchst</h3><p>Höre jeden Satz an und lies die Bedeutung. Danach wirst du aktiv getestet.</p><div class="lw48-phrase-list">${l.pairs.map(p=>`<div class="lw48-phrase"><div><strong>${esc(p.target)}</strong><span>${esc(p.base)}</span></div><button class="lw48-btn secondary" data-say="${esc(p.target)}">🔊 Anhören</button></div>`).join('')}</div><div class="lw48-actions"><button class="lw48-btn teal" id="next">Weiter</button></div>`}
 if(x.type==='mc'||x.type==='listen'){body=`<span class="lw48-stage-label">Aufgabe ${Math.max(1,step-1)} / 6</span><h3>${esc(x.prompt)}</h3>${x.type==='listen'?`<button class="lw48-btn secondary" data-say="${esc(x.say)}">🔊 Satz abspielen</button>`:''}<div class="lw48-options">${x.options.map(o=>`<button class="lw48-option" data-choice="${esc(o)}">${esc(o)}</button>`).join('')}</div><div id="feed"></div><div class="lw48-actions"><button class="lw48-btn teal" id="check" disabled>Prüfen</button></div>`}
 if(x.type==='type'){body=`<span class="lw48-stage-label">Aufgabe ${Math.max(1,step-1)} / 6</span><h3>${esc(x.prompt)}</h3><input class="lw48-input" id="typed" autocomplete="off" autocapitalize="sentences" placeholder="Antwort eingeben …"><div id="feed"></div><div class="lw48-actions"><button class="lw48-btn teal" id="check">Prüfen</button></div>`}
 if(x.type==='order'){const words=shuffled(x.answer.split(/\s+/));body=`<span class="lw48-stage-label">Aufgabe ${Math.max(1,step-1)} / 6</span><h3>${esc(x.prompt)}</h3><div class="lw48-built" id="built"><span style="color:#8a9aa7;font-size:12px">Tippe die Wörter in der richtigen Reihenfolge an.</span></div><div class="lw48-wordbank">${words.map((w,i)=>`<button class="lw48-chip" data-word="${esc(w)}" data-i="${i}">${esc(w)}</button>`).join('')}</div><div id="feed"></div><div class="lw48-actions"><button class="lw48-btn secondary" id="reset">Zurücksetzen</button><button class="lw48-btn teal" id="check">Prüfen</button></div>`}
 stage.innerHTML=body;wire(x,l)}
function wire(x,l){document.querySelectorAll('[data-say]').forEach(b=>b.onclick=()=>speak(b.dataset.say));const next=$('#next');if(next)next.onclick=()=>{step++;render()};if(x.type==='mc'||x.type==='listen'){let selected='';document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{if(locked)return;document.querySelectorAll('[data-choice]').forEach(y=>y.classList.remove('selected'));b.classList.add('selected');selected=b.dataset.choice;$('#check').disabled=false});$('#check').onclick=()=>grade(norm(selected)===norm(x.correct),x.correct)}else if(x.type==='type'){$('#typed').addEventListener('keydown',e=>{if(e.key==='Enter')$('#check').click()});$('#check').onclick=()=>grade(norm($('#typed').value)===norm(x.answer),x.answer)}else if(x.type==='order'){let built=[];const refresh=()=>{$('#built').innerHTML=built.length?built.map(w=>`<span class="lw48-chip">${esc(w)}</span>`).join(''):'<span style="color:#8a9aa7;font-size:12px">Tippe die Wörter in der richtigen Reihenfolge an.</span>'};document.querySelectorAll('[data-word]').forEach(b=>b.onclick=()=>{if(locked||b.classList.contains('used'))return;built.push(b.dataset.word);b.classList.add('used');refresh()});$('#reset').onclick=()=>{built=[];document.querySelectorAll('[data-word]').forEach(b=>b.classList.remove('used'));refresh()};$('#check').onclick=()=>grade(norm(built.join(' '))===norm(x.answer),x.answer)}}
function grade(ok,answer){if(locked)return;locked=true;if(ok)score++;const f=$('#feed');f.className='lw48-feedback '+(ok?'ok':'bad');f.innerHTML=ok?'Richtig ✓':`Fast. Die richtige Antwort ist: <strong>${esc(answer)}</strong>`;const c=$('#check');c.textContent='Weiter';c.disabled=false;c.onclick=()=>{step++;locked=false;render()}}
function finish(stage,l){const total=6,pct=Math.round(score/total*100),pass=pct>=75,stars=pct>=95?3:pct>=80?2:pct>=75?1:0;let earned=0;if(pass){let [s,ls]=langState();const first=!ls.completed[l.id];ls.completed[l.id]=true;ls.best[l.id]=Math.max(ls.best[l.id]||0,pct);ls.last=Math.min(data.lessons.length,l.id+1);if(first){earned=l.xp;ls.xp=(ls.xp||0)+earned;addGlobalXP(earned)}save(s);map();stats()}
 stage.innerHTML=`<div class="lw48-result"><span class="lw48-stage-label">Lektion abgeschlossen</span><div class="score">${pct}%</div><div class="lw48-stars">${'★'.repeat(stars)}${'☆'.repeat(3-stars)}</div><h3>${pass?'Sehr gut – bestanden!':'Noch ein Durchgang.'}</h3><p>${pass?`Du hast ${earned?earned+' XP verdient.':'deinen Bestwert bestätigt.'} Die nächste Lektion ist freigeschaltet.`:'Für das Bestehen brauchst du 75 %. Wiederhole die Lektion – beim zweiten Durchgang sitzt sie meistens deutlich besser.'}</p>${pass?'<span class="lw48-badge">🏆 A1 Fortschritt gespeichert</span>':''}<div class="lw48-actions" style="justify-content:center"><button class="lw48-btn secondary" id="again">Wiederholen</button>${pass&&l.id<data.lessons.length?'<button class="lw48-btn teal" id="nextLesson">Nächste Lektion</button>':''}</div></div>`;$('#again').onclick=startIntro;const n=$('#nextLesson');if(n)n.onclick=()=>{current=l.id+1;startIntro();map()}}
$('#lw48-map-toggle').onclick=()=>$('#lw48-map').classList.toggle('mobile-open');const [s,ls]=langState();current=Math.max(1,Math.min(data.lessons.length,Number(ls.last)||1));if(!isUnlocked(current))current=1;map();stats();startIntro();
})();