
const LANG_CODE=document.body.dataset.lang;
const LDATA=APP_DATA.languages[LANG_CODE];
const G=GRAMMAR_V23[LANG_CODE]||[];
const V=VERB_DATA[LANG_CODE]||[];
const LEVELS=["A1","A2","B1","B2","C1"];
const LEVEL_LABELS={A1:"Grundlagen",A2:"Alltag",B1:"Selbstständig",B2:"Sicher kommunizieren",C1:"Fortgeschritten"};
const KEY="sprachwerkQuest";
let state=JSON.parse(localStorage.getItem(KEY)||"{}");
state.xp ||= 0; state.dailyXP ||=0; state.lastDay ||= ""; state.completed ||= {}; state.words ||= {}; state.srs ||= {}; state.errors ||= []; state.favorites ||= {vocab:{},verbs:{}}; state.dailyTasks ||= {};
const today=new Date().toISOString().slice(0,10); if(state.lastDay!==today){state.dailyXP=0;state.lastDay=today;state.dailyTasks[today]=0;}
function save(){localStorage.setItem(KEY,JSON.stringify(state)); cloudSave(); refreshDashboard();}
let sb=null,user=null,cloudTimer=null;
async function initCloud(){const cfg=window.SUPABASE_CONFIG||{};if(!window.supabase||!cfg.url||cfg.url.includes("YOUR-PROJECT"))return;sb=window.supabase.createClient(cfg.url,cfg.publishableKey,{auth:{persistSession:true,autoRefreshToken:true}});let {data:{session}}=await sb.auth.getSession();user=session?.user||null;if(user){let {data}=await sb.from("user_progress").select("state").eq("user_id",user.id).maybeSingle();if(data?.state){state=Object.assign(state,data.state);localStorage.setItem(KEY,JSON.stringify(state));renderAll();}}}
function cloudSave(){if(!sb||!user)return;clearTimeout(cloudTimer);cloudTimer=setTimeout(()=>sb.from("user_progress").upsert({user_id:user.id,state,updated_at:new Date().toISOString()},{onConflict:"user_id"}),700)}
function grammarKey(id){return `${LANG_CODE}:g:${id-1}`}
function isComplete(id){return !!state.completed[grammarKey(id)]}
function lessonUnlocked(id){return id===1||isComplete(id-1)}
function awardXP(n){state.xp+=n;state.dailyXP+=n;state.dailyTasks[today]=(state.dailyTasks[today]||0)+1;save()}
function openPanel(id){document.querySelectorAll('.tab,.panel').forEach(x=>x.classList.remove('active'));document.querySelector(`.tab[data-tab="${id}"]`)?.classList.add('active');document.getElementById(id)?.classList.add('active');window.scrollTo({top:document.querySelector('.tabs').offsetTop-70,behavior:'smooth'})}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>openPanel(b.dataset.tab));document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openPanel(b.dataset.open));
const dlg=document.getElementById('content-dialog'),out=document.getElementById('dialog-content');document.getElementById('dialog-close').onclick=()=>dlg.close();
function currentLevel(){let done=G.filter(x=>isComplete(x.id)).length;return LEVELS[Math.min(4,Math.floor(done/4))]}
function refreshDashboard(){let done=G.filter(x=>isComplete(x.id)).length,level=currentLevel();document.getElementById('cefr-current').textContent=level;document.getElementById('cefr-copy').textContent=LEVEL_LABELS[level];document.getElementById('overall-bar').style.width=`${done/20*100}%`;document.getElementById('overall-label').textContent=`${done} / 20 Lektionen`;document.getElementById('daily-xp').textContent=`${state.dailyXP} / 50 XP`;document.getElementById('daily-bar').style.width=`${Math.min(100,state.dailyXP/50*100)}%`;document.getElementById('daily-tasks').textContent=`${state.dailyTasks[today]||0} Aufgaben abgeschlossen`;document.getElementById('due-count').textContent=getDueWords().length;document.getElementById('error-count').textContent=state.errors.filter(e=>e.lang===LANG_CODE).length;let fav=Object.keys(state.favorites.vocab||{}).filter(k=>k.startsWith(LANG_CODE+':')).length+Object.keys(state.favorites.verbs||{}).filter(k=>k.startsWith(LANG_CODE+':')).length;document.getElementById('fav-count').textContent=fav;document.getElementById('cefr-path').innerHTML=LEVELS.map(l=>{let ls=G.filter(x=>x.cefr===l),d=ls.filter(x=>isComplete(x.id)).length;return `<div class="cefr-step ${d===4?'complete':''} ${l===level?'current':''}"><b>${l}</b><small>${LEVEL_LABELS[l]} · ${d}/4</small></div>`}).join('')}
function renderGrammar(){let root=document.getElementById('grammar-levels');root.innerHTML=LEVELS.map(level=>{let ls=G.filter(x=>x.cefr===level);return `<section class="level-block"><div class="level-title"><span class="level-pill">${level}</span><strong>${LEVEL_LABELS[level]}</strong></div><div class="lesson-grid">${ls.map(x=>{let complete=isComplete(x.id),unlocked=lessonUnlocked(x.id);return `<article class="lesson-card ${complete?'complete':''} ${!unlocked?'locked':''}"><span class="badge">LEKTION ${x.id} · ${level}</span><h3>${x.title}</h3><p>${x.summary}</p><button class="open-btn" data-lesson="${x.id}" ${!unlocked?'disabled':''}>${complete?'Wiederholen':unlocked?'Lektion starten':'🔒 Vorherige Lektion abschließen'}</button></article>`}).join('')}</div></section>`}).join('');root.onclick=e=>{let b=e.target.closest('[data-lesson]');if(b&&!b.disabled)openLesson(+b.dataset.lesson)}}
function addError(error){let key=JSON.stringify([error.lang,error.type,error.lesson,error.q,error.word]);if(!state.errors.some(x=>JSON.stringify([x.lang,x.type,x.lesson,x.q,x.word])===key))state.errors.unshift({...error,created:Date.now()});save()}
function openLesson(id){let x=G.find(a=>a.id===id);out.innerHTML=`<div class="lesson-body"><span class="badge">${x.cefr} · LEKTION ${x.id}</span><span class="badge" style="margin-left:8px;background:#e9f8f3;color:#08775f">✓ Redaktionell geprüft v64</span><h2>${x.title}</h2><p>${x.summary}</p><p style="font-size:12px;color:#667085">Niveauangabe: CEFR-orientierte Lernprogression; kein offizieller CEFR-Einstufungsnachweis.</p><div class="rulebox"><strong>Grundregel</strong><br>${x.rule}</div><h3>Ausführliche Erklärung</h3>${x.explanation.map((d,i)=>`<div class="explain-step"><strong>${i+1}.</strong> ${d}</div>`).join('')}<h3>Beispiele & Transfer</h3>${x.examples.map(e=>`<div class="example"><strong>${e.kind}</strong><br>${e.target}${e.translation?`<small>${e.translation}</small>`:''}</div>`).join('')}<div class="quiz"><h3>Abschlusstest · ${x.quiz.length} Multiple-Choice-Fragen</h3>${x.quiz.map((q,i)=>`<div class="question" data-correct="${q.correct}" data-q="${i}"><strong>${i+1}. ${q.q}</strong>${q.a.map((a,j)=>`<button class="option" data-i="${j}">${a}</button>`).join('')}</div>`).join('')}<button class="open-btn" id="finish-quiz">Test auswerten</button><div class="quiz-result" id="quiz-result"></div></div></div>`;dlg.showModal();let chosen={};out.querySelectorAll('.option').forEach(btn=>btn.onclick=()=>{let q=btn.closest('.question');q.querySelectorAll('.option').forEach(o=>o.classList.remove('selected'));btn.classList.add('selected');chosen[+q.dataset.q]=+btn.dataset.i});document.getElementById('finish-quiz').onclick=()=>{let score=0;out.querySelectorAll('.question').forEach((q,i)=>{let correct=+q.dataset.correct,opts=q.querySelectorAll('.option');opts[correct].classList.add('correct');if(chosen[i]===correct)score++;else{if(chosen[i]!=null)opts[chosen[i]].classList.add('wrong');addError({lang:LANG_CODE,type:'grammar',lesson:x.id,q:x.quiz[i].q,answer:x.quiz[i].a[correct]})}});let pass=score>=Math.ceil(x.quiz.length*.8);document.getElementById('quiz-result').textContent=`${score} / ${x.quiz.length} richtig · ${pass?'Bestanden! +25 XP':'Noch nicht bestanden. Trainiere die Fehler und versuche es erneut.'}`;if(pass&&!isComplete(x.id)){state.completed[grammarKey(x.id)]=true;awardXP(25);renderGrammar();renderErrors()}}}
let words=[];(LDATA.vocab||[]).forEach((cat,ci)=>(cat.items||[]).forEach((w,wi)=>words.push({id:`${ci}:${wi}`,cat:cat.name,word:w[0],translation:w[1],example:w[2]})));
function srsKey(w){return `${LANG_CODE}:${w.id}`}
function getSrs(w){return state.srs[srsKey(w)]||{due:0,interval:0,ease:2.5,reps:0}}
function getDueWords(){let now=Date.now();return words.filter(w=>getSrs(w).due<=now).slice(0,100)}
function rateWord(w,rating){let s=getSrs(w),days={again:0,hard:1,good:Math.max(2,s.interval?Math.round(s.interval*2.2):2),easy:Math.max(4,s.interval?Math.round(s.interval*3.2):4)}[rating];s.reps=(s.reps||0)+1;s.interval=days;s.ease=Math.max(1.3,(s.ease||2.5)+(rating==='easy'?.15:rating==='hard'?-.15:rating==='again'?-.25:0));s.due=Date.now()+(rating==='again'?10*60*1000:days*86400000);state.srs[srsKey(w)]=s;state.words[`${LANG_CODE}:${w.id}`]=Math.max(state.words[`${LANG_CODE}:${w.id}`]||0,rating==='again'?1:rating==='hard'?2:3);if(rating==='again'||rating==='hard')addError({lang:LANG_CODE,type:'vocab',word:w.word,answer:w.translation});if(rating==='good'||rating==='easy')awardXP(rating==='easy'?4:3);else save();renderVocab();renderReview();}
function renderFlashcard(container,w){if(!w){container.innerHTML='<div class="flashcard"><h3>Heute nichts mehr fällig 🎉</h3><p>Du kannst trotzdem Kategorien durchsuchen oder Favoriten wiederholen.</p></div>';return}container.innerHTML=`<div class="flashcard"><span class="badge">${w.cat}</span><h3>${w.word}</h3><div class="translation">${w.translation}</div><div class="example">${w.example||''}</div><button class="fav ${state.favorites.vocab[srsKey(w)]?'active':''}" data-fav-word="${w.id}">★</button><div class="rating"><button class="again" data-rate="again">Nochmal · 10 Min</button><button data-rate="hard">Schwer · 1 Tag</button><button data-rate="good">Gut</button><button class="easy" data-rate="easy">Einfach</button></div></div>`;container.querySelectorAll('[data-rate]').forEach(b=>b.onclick=()=>rateWord(w,b.dataset.rate));container.querySelector('[data-fav-word]')?.addEventListener('click',()=>toggleVocabFav(w))}
function toggleVocabFav(w){let k=srsKey(w);if(state.favorites.vocab[k])delete state.favorites.vocab[k];else state.favorites.vocab[k]={word:w.word,translation:w.translation,cat:w.cat};save();renderFavorites();renderVocab()}
function renderVocab(){let cats=[...new Set(words.map(w=>w.cat))],sel=document.getElementById('vocab-category');if(sel.options.length===1)sel.innerHTML='<option value="">Alle Kategorien</option>'+cats.map(c=>`<option>${c}</option>`).join('');let q=document.getElementById('vocab-search').value.toLowerCase(),cat=sel.value,a=words.filter(w=>(!cat||w.cat===cat)&&(!q||(w.word+' '+w.translation).toLowerCase().includes(q))).slice(0,120);document.getElementById('vocab-grid').innerHTML=a.map(w=>`<article class="vocab-card"><button class="fav ${state.favorites.vocab[srsKey(w)]?'active':''}" data-vfav="${w.id}">★</button><span class="badge">${w.cat}</span><h3>${w.word}</h3><p>${w.translation}</p><small>${w.example||''}</small></article>`).join('');renderFlashcard(document.getElementById('vocab-review-card'),getDueWords()[0]);document.querySelectorAll('[data-vfav]').forEach(b=>b.onclick=()=>toggleVocabFav(words.find(w=>w.id===b.dataset.vfav)))}
document.getElementById('vocab-search').oninput=renderVocab;document.getElementById('vocab-category').onchange=renderVocab;
function renderReview(){let deck=document.getElementById('review-deck');renderFlashcard(deck,getDueWords()[0])}
function verbFavKey(v){return `${LANG_CODE}:${v.rank}`}
function renderVerbs(){let q=(document.getElementById('verb-search').value||'').toLowerCase();document.getElementById('verb-grid').innerHTML=V.filter(v=>v.verb.toLowerCase().includes(q)).map(v=>`<article class="verb-card"><button class="fav ${state.favorites.verbs[verbFavKey(v)]?'active':''}" data-verbfav="${v.rank}">★</button><span class="badge">#${v.rank}</span><h3>${v.verb}</h3><p>${v.translation}</p><button class="open-btn" data-verb="${v.rank}">Konjugieren</button></article>`).join('')}
document.getElementById('verb-search').oninput=renderVerbs;document.getElementById('verb-grid').onclick=e=>{let fav=e.target.closest('[data-verbfav]');if(fav){let v=V.find(x=>x.rank==fav.dataset.verbfav),k=verbFavKey(v);if(state.favorites.verbs[k])delete state.favorites.verbs[k];else state.favorites.verbs[k]={verb:v.verb,translation:v.translation};save();renderVerbs();renderFavorites();return}let b=e.target.closest('[data-verb]');if(!b)return;let v=V.find(x=>x.rank==b.dataset.verb),p=VERB_META[LANG_CODE][1],tab=(t,a)=>`<div class="tense"><h4>${t}</h4>${p.map((x,i)=>`<div class="row"><span>${x}</span><b>${a[i]}</b></div>`).join('')}</div>`;out.innerHTML=`<div class="lesson-body"><span class="badge">VERB #${v.rank}</span><h2>${v.verb}</h2><div class="tense-grid">${tab('Präsens',v.present)}${tab('Vergangenheit',v.past)}${tab('Zukunft',v.future)}</div></div>`;dlg.showModal()}
function renderErrors(){let list=document.getElementById('error-list'),es=state.errors.filter(e=>e.lang===LANG_CODE);list.innerHTML=es.length?es.map((e,i)=>`<article class="stack-item"><div><strong>${e.type==='grammar'?'Grammatik':'Vokabel'}: ${e.word||'Lektion '+e.lesson}</strong><small>${e.q||''}${e.answer?' · Richtig: '+e.answer:''}</small></div><button class="mini-btn" data-clear-error="${state.errors.indexOf(e)}">Erledigt</button></article>`).join(''):'<p>Keine offenen Fehler. Stark!</p>';list.querySelectorAll('[data-clear-error]').forEach(b=>b.onclick=()=>{state.errors.splice(+b.dataset.clearError,1);save();renderErrors()})}
function renderFavorites(){let arr=[];Object.values(state.favorites.vocab||{}).forEach(x=>arr.push({type:'Vokabel',name:x.word,sub:x.translation}));Object.values(state.favorites.verbs||{}).forEach(x=>arr.push({type:'Verb',name:x.verb,sub:x.translation}));document.getElementById('favorite-list').innerHTML=arr.length?arr.map(x=>`<article class="stack-item"><div><strong>${x.type}: ${x.name}</strong><small>${x.sub||''}</small></div></article>`).join(''):'<p>Noch keine Favoriten gespeichert.</p>'}
function renderAll(){refreshDashboard();renderGrammar();renderVocab();renderReview();renderVerbs();renderErrors();renderFavorites()}
function applyDeepLinkV62(){
  const params=new URLSearchParams(location.search);const tab=params.get('tab'),lesson=Number(params.get('lesson')||0),cat=params.get('category');
  if(tab==='grammar'){openPanel('grammar-panel');if(lesson&&G.some(x=>x.id===lesson)){setTimeout(()=>openLesson(lesson),80)}}
  if(tab==='vocab'){openPanel('vocab-panel');if(cat){const sel=document.getElementById('vocab-category');if(sel){sel.value=cat;renderVocab();setTimeout(()=>sel.scrollIntoView({behavior:'smooth',block:'center'}),80)}}}
  if(tab==='training')openPanel('review-panel');
}

document.addEventListener('DOMContentLoaded',()=>{renderAll();applyDeepLinkV62();initCloud()});
